apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: opsmx-oss
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000